### Numpy


In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4])

In [3]:
a


array([1, 2, 3, 4])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.dtype

dtype('int64')

In [6]:
a.ndim

1

In [7]:
a.size

4

In [8]:
a.shape

(4,)

In [9]:
b = np.array([[1, 2, 3],[4, 5, 6]])

In [10]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
b.ndim

2

In [12]:
b.size

6

In [13]:
b.shape

(2, 3)

In [14]:
c = np.array((1,2,3,4))

In [15]:
c

array([1, 2, 3, 4])

In [16]:
d = np.array(((1,2,3), (4,5,6)))

In [17]:
d

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
d.dtype

dtype('int64')

In [19]:
type(d)

numpy.ndarray

In [20]:
d.shape

(2, 3)

In [21]:
d.size

6

In [22]:
e = np.array(['a', 'b', 'c'])
e

array(['a', 'b', 'c'], dtype='<U1')

In [23]:
e.dtype

dtype('<U1')

In [24]:
e.size

3

In [25]:
e.shape

(3,)

In [26]:
f = np.array([1,2,3,4], dtype = complex)
f

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [27]:
f = np.array([1,2,3,4], dtype = str)
f

array(['1', '2', '3', '4'], dtype='<U1')

In [28]:
np.zeros(4,3)

TypeError: Cannot interpret '3' as a data type

In [29]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.zeros([8,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
np.ones([1,10])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [32]:
np.ones([3,5],dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [35]:
np.arange(2,4)

array([2, 3])

In [36]:
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
np.arange(1,16).reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [39]:
np.arange(2,21,2).reshape(5,2)

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20]])

In [40]:
np.random.random(2)

array([0.98472324, 0.09506075])

In [41]:
np.random.random((4,7))

array([[0.37726473, 0.29238197, 0.27589926, 0.04506344, 0.19371049,
        0.66841556, 0.42881073],
       [0.74791648, 0.0944121 , 0.99132028, 0.06787072, 0.16227644,
        0.82989734, 0.65914411],
       [0.46515303, 0.47720428, 0.77026069, 0.14036493, 0.48622878,
        0.66345465, 0.53078876],
       [0.36271425, 0.89966891, 0.60683174, 0.67761648, 0.64772846,
        0.46802933, 0.68495568]])

In [42]:
a = np.arange(4)

In [43]:
a

array([0, 1, 2, 3])

In [44]:
a+2

array([2, 3, 4, 5])

In [45]:
a-4

array([-4, -3, -2, -1])

In [46]:
a*5

array([ 0,  5, 10, 15])

In [47]:
a/4

array([0.  , 0.25, 0.5 , 0.75])

In [49]:
b = np.arange(1,10).reshape(3,3)
c = np.arange(10,19).reshape(3,3)


In [50]:
b+c


array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [51]:
c-b

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [52]:
b*c

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [53]:
b.dot(c)

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [54]:
np.dot(b,c)

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [55]:
b/c

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ],
       [0.4375    , 0.47058824, 0.5       ]])

In [56]:
a = np.arange(10,15)

In [57]:
a += 1

In [58]:
a

array([11, 12, 13, 14, 15])

In [59]:
a-= 4

In [60]:
a

array([ 7,  8,  9, 10, 11])

In [61]:
a*=10
a

array([ 70,  80,  90, 100, 110])

In [68]:
arr = np.array([2.3, 4.7, 3.2, 5.9, 7.4])
arr

array([2.3, 4.7, 3.2, 5.9, 7.4])

In [69]:
arr.sum()

np.float64(23.5)

In [70]:
arr.min()

np.float64(2.3)

In [71]:
arr.max()

np.float64(7.4)

In [72]:
arr.mean()

np.float64(4.7)

In [73]:
arr.std()

np.float64(1.8297540818372289)

In [74]:
arr1 = np.array([1,3,5,2,6,7,9])
arr1

array([1, 3, 5, 2, 6, 7, 9])

In [75]:
arr1[0]

np.int64(1)

In [76]:
arr1[2:5]

array([5, 2, 6])

In [77]:
arr1[-3]

np.int64(6)

In [79]:
arr1[1:]

array([3, 5, 2, 6, 7, 9])

In [81]:
arr1[:-1]

array([1, 3, 5, 2, 6, 7])

In [83]:
arr1[::-1]

array([9, 7, 6, 2, 5, 3, 1])

In [84]:
arr1[0:5:2]

array([1, 5, 6])

In [85]:
arr1[[1,2,3]]

array([3, 5, 2])

In [2]:
bat = np.array([10,11,12,13,14,15,16,17,18]).reshape(3,3)
bat

NameError: name 'np' is not defined

In [87]:
bat[0]

array([10, 11, 12])

In [88]:
bat[0:]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [89]:
bat[:0]

array([], shape=(0, 3), dtype=int64)

In [90]:
bat[:1]

array([[10, 11, 12]])

In [91]:
bat[0,:1]

array([10])

In [92]:
bat[1,:1]

array([13])

In [94]:
bat[2,:1]

array([16])

In [95]:
bat[:1,2]

array([12])

In [2]:
import numpy as np

In [3]:
a = np.arange(10,18)

In [4]:
for i in a:
    print(a)

[10 11 12 13 14 15 16 17]
[10 11 12 13 14 15 16 17]
[10 11 12 13 14 15 16 17]
[10 11 12 13 14 15 16 17]
[10 11 12 13 14 15 16 17]
[10 11 12 13 14 15 16 17]
[10 11 12 13 14 15 16 17]
[10 11 12 13 14 15 16 17]


In [5]:
b = np.arange(10,19).reshape(3,3)

In [6]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [7]:
for row in b:
    for j in row:
        print(j)

10
11
12
13
14
15
16
17
18


In [8]:
for i in b.flat:
    print(i)

10
11
12
13
14
15
16
17
18


In [9]:
a = np.ones((3,3))
b = np.zeros((3,3))
np.vstack((a,b))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.hstack((a,b))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [14]:
np.hstack((a,b))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [15]:
a = np.arange(16).reshape((4,4))
[b, c] = np.hsplit(a, 2)


In [16]:
b, c

(array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]))

In [17]:
[b, c] = np.vsplit(a, 2)
b, c

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]))

In [18]:
[a1, a2, a3] = np.split(a, [1, 3], axis = 1)

In [19]:
a1, a2, a3

(array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]]))

In [20]:
[a1, a2, a3] = np.split(a, [1, 3], axis = 0)

In [21]:
a1, a2, a3

(array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]))

In [22]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[10], [20]])
A + B

array([[11, 12, 13],
       [24, 25, 26]])

### Euclidean Distance

In [23]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
d = np.linalg.norm(a1 - a2)
d

np.float64(5.196152422706632)

In [24]:
a = np.array([[1,2], [3,4]])
inv_a = np.linalg.inv(a)
inv_a

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [25]:
b = np.array([[6,1], [4,-2]])
det = np.linalg.det(b)
det

np.float64(-15.999999999999998)

In [26]:
c = np.array([[4,2], [1,3]])
val, vec = np.linalg.eig(c)
val
vec

array([[ 0.89442719, -0.70710678],
       [ 0.4472136 ,  0.70710678]])

In [27]:
val

array([5., 2.])

In [28]:
vec

array([[ 0.89442719, -0.70710678],
       [ 0.4472136 ,  0.70710678]])

In [29]:
a = np.array([1,2,3,4,5])
res = np.power(a, 5)

In [30]:
res

array([   1,   32,  243, 1024, 3125])

In [31]:
a1 = np.array([1,2,3])
a2 = np.array([1,2,5])

res = np.equal(a1, a2)
res

array([ True,  True, False])

In [32]:
a = np.array([1,2,2,3,4,4,4])
res = np.unique(a)
res

array([1, 2, 3, 4])

In [33]:
a = np.array([1,2,2,3,4,4,4])
res = np.unique(a, return_counts=True)
res

(array([1, 2, 3, 4]), array([1, 2, 1, 3]))

In [34]:
uni, count = np.unique(a, return_counts=True)

In [35]:
uni

array([1, 2, 3, 4])

In [36]:
count

array([1, 2, 1, 3])

In [37]:
a = np.array([1,2,3,4,5])
r_avg = np.convolve(a, np.ones(3)/3, mode="valid")
r_avg

array([2., 3., 4.])

In [38]:
x = np.array([1,2,3])
g = np.gradient(x**2)
g 


array([3., 4., 5.])

In [39]:
x = np.array([1,2,3,4])
fft = np.fft.fft(x)
fft

array([10.+0.j, -2.+2.j, -2.+0.j, -2.-2.j])

In [40]:
ar = np.array([1, np.nan, np.inf, -np.inf])

In [41]:
ar

array([  1.,  nan,  inf, -inf])

In [42]:
is_na = np.isnan(ar)
is_na

array([False,  True, False, False])

In [43]:
is_inf = np.isinf(ar)
is_inf

array([False, False,  True,  True])

In [44]:
sum(is_na)

np.int64(1)

In [45]:
sum(is_inf)

np.int64(2)